@include ('dashboard.layouts.start')
@include ('dashboard.layouts.slideBar')
@include ('dashboard.layouts.header')
@include ('dashboard.layouts.content')
@include ('dashboard.layouts.deleteModal')
@include ('dashboard.layouts.end')
